language: go

sudo: false

go:
  - 1.11.x
  - 1.12.x
  - master

git:
  depth: 1

before_install:
  - go get -v -t -d ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false