language: go

sudo: false

go:
  - 1.13.x
  - 1.14.x

git:
  depth: 1

before_install:
  - go get -v -t -d ./...
  - go get github.com/mattn/goveralls

notifications:
  email: false

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci
