language: go

sudo: false

go:
  - tip

git:
  depth: 1

before_install:
  - go get -v -t -d ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v -race ./...

notifications:
  email: false